spring:
  application:
    name: cinemaxx
  datasource:
    hikari:
      connection-timeout: 20000
      idle-timeout: 10000
      max-lifetime: 600000
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5432/cinemaxx
    username: admin
    password: admin
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 100
        order_inserts: true
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: false
  packages-to-scan: com.academy.cinemaxx.controllers

server:
  port: 8080

minio:
  url: http://127.0.0.1:9000
  access-key: TWgkv9AlcqhsF5g4sjXN
  access-secret: D9FSZjFpLqV5cYoogN2fKKB2FliNwTYhffPKZif1
  bucket-name: cinemaxx
  
mail:
  smtp:
    host: sandbox.smtp.mailtrap.io
    port: 587
    auth: true
    ssl:
      trust: sandbox.smtp.mailtrap.io
    starttls:
      enable: true
  username: a41e01591f6715
  password: 93336af2fe6cec

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 30
  refresh:
    expiration: 7