INSERT INTO public.cinema (name, address, city_id, secure_id, created_at, updated_at)
VALUES 
('XXI Plaza Indonesia', 'Jl. MH Thamrin No.28-30, Jakarta', 1, gen_random_uuid(), now(), now()),
('CGV Grand Indonesia', 'Jl. MH Thamrin No.1, Jakarta Pusat', 1, gen_random_uuid(), now(), now()),
('Cinepolis Pejaten Village', 'Jl. Warung Jati Barat No.39, Pasar Minggu, Jakarta Selatan', 1, gen_random_uuid(), now(), now()),
('XXI Gandaria City', 'Jl. Sultan Iskandar Muda, Kebayoran Lama, Jakarta Selatan', 1, gen_random_uuid(), now(), now()),
('CGV Pacific Place', 'Jl. Jenderal Sudirman Kav. 52-53, SCBD, Jakarta Selatan', 1, gen_random_uuid(), now(), now()),
('XXI Kota Kasablanka', 'Jl. Casablanca Raya Kav. 88, Tebet, Jakarta Selatan', 1, gen_random_uuid(), now(), now()),
('CGV FX Sudirman', 'Jl. Jenderal Sudirman Pintu Satu Senayan, Jakarta Pusat', 1, gen_random_uuid(), now(), now()),
('XXI Artha Gading', 'Jl. Boulevard Artha Gading No.A1, Kelapa Gading, Jakarta Utara', 1, gen_random_uuid(), now(), now()),
('CGV Green Pramuka Mall', 'Jl. Jend. Ahmad Yani, Rawasari, Jakarta Pusat', 1, gen_random_uuid(), now(), now()),
('XXI Mall Taman Anggrek', 'Jl. Letjen S. Parman, Grogol Petamburan, Jakarta Barat', 1, gen_random_uuid(), now(), now()),
('XXI Blok M Plaza', 'Jl. Bulungan No.76, Kebayoran Baru, Jakarta Selatan', 1, gen_random_uuid(), now(), now()),
('CGV Transmart Cempaka Putih', 'Jl. Letjen Suprapto No.1, Jakarta Pusat', 1, gen_random_uuid(), now(), now()),
('Cinepolis Baywalk Mall', 'Jl. Pluit Karang Ayu 1 No.B1, Jakarta Utara', 1, gen_random_uuid(), now(), now()),
('XXI Lippo Mall Puri', 'Jl. Puri Indah Raya Blok U1, Kembangan, Jakarta Barat', 1, gen_random_uuid(), now(), now()),
('CGV Aeon Mall JGC', 'Jl. Jl. Raya Cakung Cilincing, Cakung, Jakarta Timur', 1, gen_random_uuid(), now(), now()),
('XXI Kalibata City', 'Jl. Kalibata Raya No.1, Jakarta Selatan', 1, gen_random_uuid(), now(), now()),
('Cinepolis Cilandak Town Square', 'Jl. TB Simatupang, Jakarta Selatan', 1, gen_random_uuid(), now(), now()),
('CGV Bella Terra Lifestyle Center', 'Jl. Boulevard Raya, Kelapa Gading, Jakarta Utara', 1, gen_random_uuid(), now(), now()),
('XXI Bassura City', 'Jl. Basuki Rahmat, Cipinang Besar Selatan, Jakarta Timur', 1, gen_random_uuid(), now(), now()),
('CGV Cinemas Central Park', 'Jl. Letjen S. Parman, Grogol Petamburan, Jakarta Barat', 1, gen_random_uuid(), now(), now()),
('XXI Trans Studio Mall Bandung', 'Jl. Gatot Subroto No.289, Bandung', 2, gen_random_uuid(), now(), now()),
('CGV Paris Van Java', 'Jl. Sukajadi No.137-139, Bandung', 2, gen_random_uuid(), now(), now()),
('Cinepolis Festival Citylink', 'Jl. Peta No.241, Bandung', 2, gen_random_uuid(), now(), now()),
('XXI Cihampelas Walk', 'Jl. Cihampelas No.160, Bandung', 2, gen_random_uuid(), now(), now()),
('CGV 23 Paskal Shopping Center', 'Jl. Pasir Kaliki No.25-27, Bandung', 2, gen_random_uuid(), now(), now()),
('XXI Braga CityWalk', 'Jl. Braga No.99-101, Bandung', 2, gen_random_uuid(), now(), now()),
('CGV BEC Mall', 'Jl. Purnawarman No.13-15, Bandung', 2, gen_random_uuid(), now(), now()),
('Cinepolis Bandung Indah Plaza', 'Jl. Merdeka No.56, Bandung', 2, gen_random_uuid(), now(), now()),
('XXI PVJ (Paris Van Java)', 'Jl. Sukajadi No.137-139, Bandung', 2, gen_random_uuid(), now(), now()),
('CGV Metro Indah Mall', 'Jl. Soekarno-Hatta No.590, Bandung', 2, gen_random_uuid(), now(), now()),
('XXI Tunjungan Plaza 5', 'Jl. Basuki Rahmat No.8-12, Surabaya', 3, gen_random_uuid(), now(), now()),
('CGV Marvell City', 'Jl. Ngagel No.123, Surabaya', 3, gen_random_uuid(), now(), now()),
('XXI Galaxy Mall', 'Jl. Dharmahusada Indah Timur No.35, Surabaya', 3, gen_random_uuid(), now(), now()),
('Cinepolis City of Tomorrow', 'Jl. Ahmad Yani No.288, Surabaya', 3, gen_random_uuid(), now(), now()),
('XXI Ciputra World Surabaya', 'Jl. Mayjend Sungkono No.87-89, Surabaya', 3, gen_random_uuid(), now(), now()),
('CGV BG Junction', 'Jl. Bubutan No.1-7, Surabaya', 3, gen_random_uuid(), now(), now()),
('XXI Pakuwon Mall', 'Jl. Puncak Indah Lontar No.2, Surabaya', 3, gen_random_uuid(), now(), now()),
('CGV Royal Plaza', 'Jl. Ahmad Yani No.16-18, Surabaya', 3, gen_random_uuid(), now(), now()),
('Cinepolis Lenmarc Mall', 'Jl. Bukit Darmo Golf, Surabaya', 3, gen_random_uuid(), now(), now()),
('XXI Grand City Mall', 'Jl. Walikota Mustajab No.1, Surabaya', 3, gen_random_uuid(), now(), now()),
('XXI Sun Plaza', 'Jl. KH Zainul Arifin, Medan', 4, gen_random_uuid(), now(), now()),
('Cinepolis DP Mall', 'Jl. Pemuda, Semarang', 5, gen_random_uuid(), now(), now()),
('XXI Ambarukmo Plaza', 'Plaza Ambarukmo, Yogyakarta', 6, gen_random_uuid(), now(), now()),
('XXI Palembang Icon', 'Palembang Icon Mall, Palembang', 7, gen_random_uuid(), now(), now()),
('CGV Panakkukang', 'Mall Panakkukang, Makassar', 8, gen_random_uuid(), now(), now()),
('XXI Level 21 Mall', 'Jl. Teuku Umar No.1, Denpasar', 9, gen_random_uuid(), now(), now()),
('XXI SKA Mall', 'Jl. Soekarno-Hatta, Pekanbaru', 10, gen_random_uuid(), now(), now()),
('XXI Kota Kasablanka', 'Mall Kota Kasablanka, Jakarta', 1, gen_random_uuid(), now(), now()),
('CGV 23 Paskal', '23 Paskal Shopping Center, Bandung', 2, gen_random_uuid(), now(), now()),
('XXI Grand City', 'Grand City Mall, Surabaya', 3, gen_random_uuid(), now(), now()),
('XXI Centre Point', 'Centre Point Mall, Medan', 4, gen_random_uuid(), now(), now()),
('Cinepolis Java Mall', 'Java Mall, Semarang', 5, gen_random_uuid(), now(), now()),
('XXI Jogja City Mall', 'Jogja City Mall, Yogyakarta', 6, gen_random_uuid(), now(), now()),
('XXI Palembang Square', 'Palembang Square Mall, Palembang', 7, gen_random_uuid(), now(), now()),
('XXI Trans Studio', 'Trans Studio Makassar, Makassar', 8, gen_random_uuid(), now(), now()),
('Cinepolis Park 23', 'Park 23 Mall, Denpasar', 9, gen_random_uuid(), now(), now()),
('XXI Ciputra Seraya', 'Ciputra Seraya Mall, Pekanbaru', 10, gen_random_uuid(), now(), now());
