INSERT INTO public.city (name, code, created_at, updated_at)
VALUES 
('Jakarta', 'JKT', now(), now()),
('Bandung', 'BDG', now(), now()),
('Surabaya', 'SBY', now(), now()),
('Medan', 'MDN', now(), now()),
('Semarang', 'SEM', now(), now()),
('Yogyakarta', 'YOG', now(), now()),
('Palembang', 'PAL', now(), now()),
('Makassar', 'MAK', now(), now()),
('Denpasar', 'DEN', now(), now()),
('Pekanbaru', 'PEK', now(), now()),
('Balikpapan', 'BAL', now(), now()),
('Malang', 'MAL', now(), now()),
('Manado', 'MAN', now(), now()),
('Batam', 'BAT', now(), now()),
('Pontianak', 'PON', now(), now()),
('Padang', 'PAD', now(), now()),
('Banjarmasin', 'BAN', now(), now()),
('Bogor', 'BOG', now(), now()),
('Cirebon', 'CIR', now(), now()),
('Kupang', 'KUP', now(), now());