INSERT INTO public.seat (
  label, row_index, column_index, hall_id, seat_element_id, status,
  secure_id, created_at, updated_at
)
VALUES
('A1', 1, 1, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('A2', 1, 2, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('A3', 1, 3, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('A4', 1, 4, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('A5', 1, 5, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('A6', 1, 6, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('A7', 1, 7, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('A8', 1, 8, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('A9', 1, 9, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('A10', 1, 10, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),

('B1', 2, 1, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('B2', 2, 2, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('B3', 2, 3, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('B4', 2, 4, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('B5', 2, 5, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('B6', 2, 6, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('B7', 2, 7, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('B8', 2, 8, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('B9', 2, 9, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('B10', 2, 10, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),

('C1', 3, 1, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('C2', 3, 2, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('C3', 3, 3, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('C4', 3, 4, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('C5', 3, 5, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('C6', 3, 6, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('C7', 3, 7, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('C8', 3, 8, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('C9', 3, 9, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('C10', 3, 10, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),

('D1', 4, 1, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('D2', 4, 2, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('D3', 4, 3, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('D4', 4, 4, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('D5', 4, 5, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('D6', 4, 6, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('D7', 4, 7, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('D8', 4, 8, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('D9', 4, 9, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('D10', 4, 10, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),

('E1', 5, 1, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('E2', 5, 2, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('E3', 5, 3, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('E4', 5, 4, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('E5', 5, 5, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('E6', 5, 6, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('E7', 5, 7, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('E8', 5, 8, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('E9', 5, 9, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('E10', 5, 10, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),

('F1', 6, 1, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('F2', 6, 2, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('F3', 6, 3, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('F4', 6, 4, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('F5', 6, 5, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('F6', 6, 6, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('F7', 6, 7, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('F8', 6, 8, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('F9', 6, 9, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('F10', 6, 10, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),

('G1', 7, 1, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('G2', 7, 2, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('G3', 7, 3, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('G4', 7, 4, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('G5', 7, 5, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('G6', 7, 6, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('G7', 7, 7, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('G8', 7, 8, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('G9', 7, 9, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now()),
('G10', 7, 10, 1, 1, 'AVAILABLE', gen_random_uuid(), now(), now())